name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o gox -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Cross build
      run: mkdir release && gox -ldflags="-w -s" -output="release/{{.Dir}}_{{.OS}}_{{.Arch}}"
      
    - name: Publish the Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: release/*
          prerelease: true 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
